### ISSUE TITLE
Third-Party Applications shouldn't provide user's card details

### ISSUE THREAD

**Issue by ibrahimlawal** [PaystackHQ/paystack-android#1]
The library currently allows the andorid dev send card details. third-party being in contact with the card details isn’t something we should allow, i believe

**Comment by ibrahimlawal** [comment]
Turns out PCI compliance is not about the thirdparty app seeing or not seeing user's card details. It's about the User's card details never reaching the thirdparty app server.

**Comment by ribads** [comment]
This actually makes sense. Because truth is that some developer might for whatever reason feel the need to save user card details on his own server. 
God forbid he server gets hacked 
I believe it's just best to provide an abstracted UI for card details capturing that returns the token
