### ISSUE TITLE
Charge Exception Error with Paystack SDK

### ISSUE THREAD

**Issue by maximuskay2** [PaystackHQ/paystack-android#101]
![Screenshot from 2020-05-04 20-03-28-1](https://user-images.githubusercontent.com/4710692/80998576-17b25800-8e3b-11ea-8825-0a895e6562ac.png)

**Comment by neerajthakur** [comment]
I'm getting the same error. Though when using the same card for live payment on website it's working fine but not in the android paystack SDK with same live credentials.

**Comment by ismailnurudeen** [comment]
Make sure you're not trying to use test credential (i.e public key) with a real card, it will not work.
Use the testing cards instead.
