### ISSUE TITLE
Charge error - Unable to process transaction

### ISSUE THREAD

**Issue by rohitsinglailluminz** [PaystackHQ/paystack-android#108]
**In Android Paystack SDK -**
Getting "Unable to process transaction" error message in case of live payment, but everything working fine in case of Test Mode.
I have updated the live keys and also using the same card for live payment on website it's working fine but not in the android paystack SDK with same live credentials.

**Comment by michael-paystack** [comment]
Hi @rohitsinglailluminz,
I'm sorry you're experiencing this issue.
Please let me know what version of this SDK you're using so I can try to reproduce it.

**Comment by rohitsinglailluminz** [comment]
Hi @michael-paystack ,
i am using these versions of the SDK - 
    implementation 'co.paystack.android.design.widget:pinpad:1.0.1'
    implementation 'co.paystack.android:paystack:3.0.12'

**Comment by olajhidey** [comment]
Sorry any update on this?

**Comment by michael-paystack** [comment]
Yes, @olajhidey. You shouldn't experience this problem if you're using the latest version of the SDK.
You shouldn't need to include the `pinpad` artifact too.
I'm sorry for the late response. 
Please let me know if you have any issues.

**Comment by chibuezedev** [comment]
Have this issue being ressolved? got this error on my checkout page, dont know whats wrong.
