### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by mexyik** [PaystackHQ/paystack-android#110]
Error: cannot find symbol import com.creativemexyrestorer.ui.AddressVerificationActivity;

symbol: class AddressVerificationActivity
location: package com.creativemexy.restorder.ui

TransactionManager.java:398
Error: cannot find symbol Intent I = new Intent(activity, AddressVerificationActivity.class);
Symbol: class AddressVerificationActivity
location: class TransactionManager.AddressVerificationAsyncTask

**Comment by michael-paystack** [comment]
Hi @mexyik,
Thanks a lot for filing this issue. I just need to know a few things so I can try to reproduce this issue.
1. What language are you developing in?
2.  Are you running Proguard or R8 on your builds?

**Comment by mexyik** [comment]
Java
Proguard

**Comment by michael-paystack** [comment]
Hello @mexyik, this issue has been fixed in later versions of the SDK.
I'm closing this now. Please open another issue if you run into any problems
