### ISSUE TITLE
This library is not compiling for Android 5.0 

### ISSUE THREAD

**Issue by FECHNOLOGIES** [PaystackHQ/paystack-android#113]
# Problem/Motivation
Library not compiling for Android 5.0 

## Proposed resolution
(Description of the proposed solution, the rationale behind it, and workarounds for people who cannot use the patch.)

## Repeatable
Always|Sometimes|Specific conditions|Specific times

(If it is a bug, you are reporting lease specify:)

## Steps to repeat: (Describe how the issue can be repeated by someone who is to work on it)
1. Step 1
2. Step 2
3. ...

## Expected Results:
(What you expected steps 1, 2 and 3 to give)

## Actual Results:
(What is gave including any error messages, memory dump etc that can help)

**Comment by michael-paystack** [comment]
@FECHNOLOGIES Can you please post the error message you see, the library version, and your target SDK version?

**Comment by michael-paystack** [comment]
Closed due to inactivity
