### ISSUE TITLE
Mobile Money Support

### ISSUE THREAD

**Issue by nivla360** [PaystackHQ/paystack-android#115]
I've been going through the documentation for this library all I see is how to charge a card how about mobile money payments?

**Comment by senyo-motey** [comment]
has the issue been solved? cos I would like to use the mobile money feature too

**Comment by steve-paystack** [comment]
Hello @nivla360 @senyo-motey our SDK's only support card payments at the moment. If you will like to integrate mobile money, I will recommend using the charge endpoint directly. Here's the docs - https://paystack.com/docs/payments/payment-channels/#mobile-money

**Comment by senyo-motey** [comment]
thank you for quick response. am grateful
