### ISSUE TITLE
Migrate library away from Bintray

### ISSUE THREAD

**Issue by claucookie** [PaystackHQ/paystack-android#116]
# Problem
As you probably know `jcenter` & `bintray` are sunsetting https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ :)

It would be good to have `co.paystack.android:paystack:3.1.2` in maven central instead.

**Comment by michael-paystack** [comment]
Hello, @claucookie! 
Thanks a lot for bringing this up. We're aware of the shutdown and have plans to migrate to MavenCentral soon.

**Comment by jumaallan** [comment]
@michael-paystack Was this closed by this [PR?](https://github.com/PaystackHQ/paystack-android/pull/119)

**Comment by danielbanks** [comment]
@michael-paystack Could you please update us on the status of this migration

**Comment by michael-paystack** [comment]
Hi @danielbanks,
We now have binaries on MavenCentral. I'll be updating the documentation to reflect this.

**Comment by michael-paystack** [comment]
@jumaallan I'm sorry I missed your comment.
Yes. That PR handles the issue. We have binaries for this library on MavenCentral. 

I'll be closing this now.
