### ISSUE TITLE
Since Charge object has amount as Integer so how to make decimal charges ?

### ISSUE THREAD

**Issue by yadav-shivam** [PaystackHQ/paystack-android#129]
# Problem/Motivation
(Why the issue was filed, steps to reproduce the problem, etc.)

## Proposed resolution
(Description of the proposed solution, the rationale behind it, and workarounds for people who cannot use the patch.)

## Repeatable
Always|Sometimes|Specific conditions|Specific times

(If it is a bug, you are reporting lease specify:)

## Steps to repeat: (Describe how the issue can be repeated by someone who is to work on it)
1. Step 1
2. Step 2
3. ...

## Expected Results:
(What you expected steps 1, 2 and 3 to give)

## Actual Results:
(What is gave including any error messages, memory dump etc that can help)

**Comment by blundell** [comment]
@yadav-shivam which countries currency are you needing to use fractional amounts with?

**Comment by michael-paystack** [comment]
Hi @yadav-shivam, the amount required should be in sub-units of the currency you're charging (Cents instead of Dollars or Kobo instead of Naira). Multiplying the charge amount by 100 should be all that's needed to get the correct amount.
