### ISSUE TITLE
How to make payment to Sub accounts using the Android SDK

### ISSUE THREAD

**Issue by po10cio** [PaystackHQ/paystack-android#14]
# Problem/Motivation
I have checked the android SDK doc, i cant see where Sub account payment is captured in it, does it mean it is not possible with the android SDK

## Proposed resolution
I think the SDK should offer support for SubAccount payment.

**Comment by jerryhanks** [comment]
I have seen it, it is in the comment, i think it is an important feature and should not be in the comment

**Comment by ibrahimlawal** [comment]
hey @jerryhanks Thanks!
