### ISSUE TITLE
Unable to resolve host "standard.paystack.co": No address associated with hostname

### ISSUE THREAD

**Issue by edwinsong31** [PaystackHQ/paystack-android#143]
I'm getting this error on the Android version. I'm using a public test key.
![image](https://user-images.githubusercontent.com/94693922/174514467-3666c9e3-ff26-4278-9e66-e94597d5849f.png)

**Comment by michael-paystack** [comment]
@edwinsong31 this looks like a problem related to connectivity issues.

**Comment by michael-paystack** [comment]
I'll close this now because it's been open for quite a while. Please open a different issue if it's still a problem
