### ISSUE TITLE
New SDK Update has no clear changelog and SDK breaks the application.

### ISSUE THREAD

**Issue by stonekase** [PaystackHQ/paystack-android#15]
# Problem/Motivation
(Why the issue was filed, steps to reproduce the problem, etc.)

## Proposed resolution
(Description of the proposed solution, the rationale behind it, and workarounds for people who cannot use the patch.)

Transaction Class was moved out of a whole namespace and was not stated in the Changelog.Its really sad.

**Comment by ibrahimlawal** [comment]
Good morning,

We will update the changelog later today. The update is a major release and will break createToken-dependent apps. As for chargeCard dependent ones, only the signature of the `onError` method has changed to allow a transaction object.

-----Original Message-----

**Comment by ibrahimlawal** [comment]
Hello @stonekase,

Did the response above help you ensure compatibility?

**Comment by stonekase** [comment]
Apologies for the late response.As usual ,i have already fixed it before raising the issue.It was more of a pointer for others to note.
