### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lco/paystack/android/ui/PinAxtivity;

### ISSUE THREAD

**Issue by Candid-emeka** [PaystackHQ/paystack-android#158]
dependency {
impleamentation 'co.paystack.android:paystack:3.1.2'
implementation 'co.paystack.android.design.widget:pinpad:1.0.4'
}

but after encountering some errors which i solved i got another error which has been giving me a serious issues
java.lang.RuntimeException: An error occurred while executing doInBackground()
...
caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lco/paystack/android/ui/PinAxtivity

can it be resolved

**Comment by michael-paystack** [comment]
@Candid-emeka Please can you update to a more recent version of paystack-android and the pinpad?
The latest version of the pinpad is `1.0.8`. We're up to version `3.3.2` for paystack-android

**Comment by Candid-emeka** [comment]
i have resolve it @michael-paystack i got a java PinActivity for the project, so instead of using the class i redirected it to read from the java file and it worked well
 thanks alot for replying
