### ISSUE TITLE
Android "Unspecified Failure" with Visa cards

### ISSUE THREAD

**Issue by sundayefeh** [PaystackHQ/paystack-android#16]
# Problem/Motivation
I always get this error "Unspecified Failure" each time i charge with Visa card on android native application.

## Proposed resolution
(Description of the proposed solution, the rationale behind it, and workarounds for people who cannot use the patch.)

## Repeatable
Always|Sometimes|Specific conditions|Specific times

(If it is a bug, you are reporting lease specify:)

## Steps to repeat: (Describe how the issue can be repeated by someone who is to work on it)
1. Step 1
2. Step 2
3. ...

## Expected Results:
(What you expected steps 1, 2 and 3 to give)

## Actual Results:
(What is gave including any error messages, memory dump etc that can help)

**Comment by ibrahimlawal** [comment]
Hello @sundayefeh Apologies for the tardy response. Please let me know if you still got this error recently

**Comment by phalconVee** [comment]
This issue still persists. In my case, i am not given an error message, nothing happens and no transaction take place. For Visa Cards

**Comment by ibrahimlawal** [comment]
Hey @sundayefeh, My bad! Should have given you an update since earlier. 

1. All Visa cards now expect at least 2 naira for a successful charge
2. Please use V3.0.4 in your app

@phalconVee that is super weird. please use your logs to see if the SDK gets called at all

**Comment by phalconVee** [comment]
Please i don't understand, can you elaborate still

   1. All Visa cards now expect at least 2 naira for a successful charge:
   is this from the users axxount
   2. Please use V3.0.4 in your app: i integrated january of this year, do
   i till need to update to V3.0.4?


Cheers!!

**Comment by phalconVee** [comment]
Please i don't understand, can you elaborate still
All Visa cards now expect at least 2 naira for a successful charge: is this from the users axxount
Please use V3.0.4 in your app: i integrated january of this year, do i till need to update to V3.0.4?

Cheers!!

**Comment by ibrahimlawal** [comment]
If you try a charge of less than 2 naira on a visa card, it will fail with message: "Unspecified failure". This has been happening since March 10 2017

**Comment by ibrahimlawal** [comment]
Yes @phalconVee you need to update :)
