### ISSUE TITLE
PaystackSdk.chargeCard() should specify the possible exceptions

### ISSUE THREAD

**Issue by larikraun** [PaystackHQ/paystack-android#18]
PaystackSdk.chargeCard(...) throws CustomException{
....
}

This will make the developers aware and catch adequately.

**Comment by ibrahimlawal** [comment]
Hey @larikraun chargeCard itself throws no exceptions, does it?

**Comment by larikraun** [comment]
@ibrahimlawal The methods it calls throws exceptions when card is null, when amount is less than 5000

**Comment by ibrahimlawal** [comment]
@larikraun All PaystackExceptions are Runtime Exceptions. However, regarding amount too low, I think you must have an old version to be getting that. We have removed that in recent versions as it wasn't supposed to make it into production.

Will look to ensure all Exceptions are documented. Thanks!

**Comment by larikraun** [comment]
@ibrahimlawal thanks for the information

**Comment by ibrahimlawal** [comment]
Glad to be of assistance boss @larikraun thanks!
