### ISSUE TITLE
OTP Dialog disappears when you leave the app to retrieve your OTP

### ISSUE THREAD

**Issue by rrbrambley** [PaystackHQ/paystack-android#19]
# Problem/Motivation
Problem: You cannot succeed in entering the OTP if you leave the app.

## Steps to repeat:
1. Using the Android SDK, specify `"enforce_otp": true` on the Charge object, e.g.
>         Charge charge = new Charge();
>         charge.setCard(card);
>         charge.setEmail(email);
>         charge.setAmount((int) (amount * 100.0f));
>         charge.setReference(reference);
>         charge.addParameter("enforce_otp", "true");
2. Execute PaystackSdk.chargeCard() using the Charge object created in step 1.
3. When the OTP dialog appears and you receive the OTP via SMS or email, leave the app to get retrieve the OTP.
4. Return to the app and see that the OTP dialog is gone.

## Repeatable
Always

## Expected Results:
The OTP dialog should persist.
Bonus: The OTP window shrinks when the keyboard is shown. Even when it hasn't shrunk, window tends to cut off some text on the edges. Perhaps include an option to show a full Activity instead of a small window?

**Comment by ibrahimlawal** [comment]
@rrbrambley since we use a synchronized lock to keep the transaction active in the SDk, keeping the app paused in the background will use up resources so we release in the SDK. We have done an update that does the releasing in onDestroy rather than onPause. Let me know if this resolves the issue

**Comment by rrbrambley** [comment]
@ibrahimlawal Releasing on onDestroy() instead of onPause() appears to be working for us. Thanks.

**Comment by ibrahimlawal** [comment]
Glad that works!
