### ISSUE TITLE
Collection and validation of card details

### ISSUE THREAD

**Issue by cititech** [PaystackHQ/paystack-android#20]
# Problem/Motivation
In your documentation on the above topic, you said the developer needs to provide the  fields on our apps activity that collect the card details. this I think is dangerous and customer might feel uncomfortable supplying their card details within an app. knowing the developer can compromise the details.

## Proposed resolution
I propose that you provide an interface from you end that apps can connect to for payment and the apps get a callback when the transaction is over.

**Comment by ibrahimlawal** [comment]
Hey @cititech thanks for reporting this. We will work on something over the long weekend.

**Comment by stonekase** [comment]
this was never worked on?

**Comment by ibrahimlawal** [comment]
@stonekase it was, we only shelved the idea pending a possible update that allows you do paywithbank from the SDK. Are you willing to help give feedback? It's on the https://github.com/PaystackHQ/paystack-android/tree/feature/card-validation branch

**Comment by stonekase** [comment]
@ibrahimlawal Actually i have been waiting for the Paywithbank as it is a wonderful idea for some payments.I will add,test and revert.

Best regards

**Comment by krushalikevadiya** [comment]
Please provide some interface that collect user card detail and also add pay with bank option.I need this please provide some way.

**Comment by michael-paystack** [comment]
@krushalikevadiya We're working on a solution for this and should share a beta in the coming days.
I'm closing this issue now, but I'll add a comment here as soon as that's ready
