### ISSUE TITLE
Code snippet to initiate transaction locally on Android

### ISSUE THREAD

**Issue by calistus** [PaystackHQ/paystack-android#21]
# Problem/Motivation
I need a code snippet or sample project to initiate transaction on the SDK. The example on the repo only does the transaction on a backend server. 
## Proposed resolution
Some App may not have a backend server and the may only be one programmer who does not write web languages

## Expected Results:
1. A second Activity class within the example(sample) project that initiate a transaction on the SDK. 
That is a class within here: https://github.com/PaystackHQ/paystack-android/tree/master/example/src/main/java/co/paystack/example

**Comment by Ebuka-Onyekwe** [comment]
I completely agree with Mr Calistus... I am an Android developer and i have been trying to implement paystack on my app. I have no experience in web languages and I am stuck on how to configure the heroku driven node.js sample code to suite me. If there was a local way that made use of java to set up quickly it would be much easier for developers without having to hire extra hands and incurring costs to implement.

**Comment by ibrahimlawal** [comment]
hey @calistus @Ebuka-Onyekwe Working on one now. Thanks for the bump @Ebuka-Onyekwe

**Comment by ibrahimlawal** [comment]
We would however encourage that you do not depend entirely on your app when handling payments. Making sure there is a backend to your app's payments reduces fraud greatly depending on the kind of service/goods you offer.

This may not be relevant to donation apps, but if giving value, having a backend that validates the transactions will be oh so comforting

**Comment by Ebuka-Onyekwe** [comment]
Excellent point Mr Ibrahim. It's always safer to host transaction code remotely but as you also mentioned, some types of apps are quite straightforward and don't require much logic. My point is the option to locally initialize transactions should be available for such simple apps. Also in my company I have a php developer that would have helped. Is node.js the only available language for android backend?

**Comment by ibrahimlawal** [comment]
@Ebuka-Onyekwe Nope, of course our APIs are not server-language agnostic. All languages can be used to call our API.

What's your PHP developer saying about making a backend for you? Making one can be really straightforward.

**Comment by Ebuka-Onyekwe** [comment]
Well for one, he doesn't know node.js so he is unable to replicate what you have. If you could have a php sample just like what you have for node.js he would be able to tweak it to my specifications. Is there any available php alternative I could forward to him?

**Comment by calistus** [comment]
I also need a phone sample. We have a backend Dev too but he is a phone
developer.
You you there are more photos developers than node so it will make sense to
have a sample backend code written with PHP too.

On 5 Jun 2017 6:56 p.m., "Ebuka" <notifications@github.com> wrote:

Well for one, he doesn't know node.js so he is unable to replicate what you
have. If you could have a php sample just like what you have for node.js he
would be able to tweak it to my specifications. Is there any available php
alternative I could forward to him?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/PaystackHQ/paystack-android/issues/21#issuecomment-306257995>,
or mute the thread

**Comment by ibrahimlawal** [comment]
Anyways, here's all that needs to change in order to start the transaction on your app:

1. Comment or delete the call to `new fetchAccessCodeFromServer()` when starting the transaction.
2. Move these lines 
```java
       charge.setCard(card);
       chargeCard();
```
to the `startAFreshCharge()` function.
3. Between the two lines above, set all parameters on the charge as required for your transaction.
4. Comment or delete the call to `new verifyOnServer()` in the `onSuccess` function.

**Comment by ibrahimlawal** [comment]
Your PHP Developer can use the sample backend in the code here: https://github.com/PaystackHQ/PaystackJS-Sample-code as a guide for his PHP development. 

These in particular:

https://github.com/PaystackHQ/PaystackJS-Sample-code/blob/137347c594ab3a5bcc82645cf046b8fdf9f57492/index.php#L15

and

https://github.com/PaystackHQ/PaystackJS-Sample-code/blob/137347c594ab3a5bcc82645cf046b8fdf9f57492/index.php#L47

**Comment by ibrahimlawal** [comment]
Hope that helps. Thank you for choosing Paystack.

**Comment by Ebuka-Onyekwe** [comment]
Excellent feedback. Thank you Mr Ibrahim, however wouldn't the paystack sdk throw an exception if server url is not added?

**Comment by Ebuka-Onyekwe** [comment]
Or I just remove the exception throw clause from source code?

**Comment by ibrahimlawal** [comment]
@Ebuka-Onyekwe yes, just remove the check too. My bad for not including that. Updating the instructions above

**Comment by Ebuka-Onyekwe** [comment]
Seen. Thanks.
I will revert if any issues.

**Comment by ibrahimlawal** [comment]
Please let us know if it works for you :)

**Comment by Ebuka-Onyekwe** [comment]
Yes it does work. 👍

**Comment by ray86** [comment]
@ibrahimlawal 
AN OBSERVATION
When Trying to initiate a transaction on android without a backend, 
i think the documentation here is not clear enough or is there another link where we can get a thorough documentation. 
The charge class requires 
setEmail(String);
setAmount(int);
 setCurrency(String);
which wasnt specified in the documentation.
Besides that, How do we send OTP? didnt clearly understand that either.

I am trying to implement in an android app that doesnt require a backend.
 Thank you.

**Comment by mbmyke** [comment]
I'm getting "Could not find class 'co.paystack.android.TransactionManager$1', referenced from method co.paystack.android.TransactionManager.<init>"

**Comment by ibrahimlawal** [comment]
This is unrelated to the title of this issue. Kindly repost as a new issue. Remember to specify the version of your android studio as well as the version of all plugins in use. Java version etc. Generally, updated versions tend to fix these.

-----Original Message-----

**Comment by sparsh77** [comment]
getting the  error "Token Authorization Not Successful. Incorrect Token Supplied" in th testing mode ,
followed the credentials on "https://developers.paystack.co/docs/test-cards" IN+PHONE+OTP validation
