### ISSUE TITLE
Pin or OTP Verification dialog closes 

### ISSUE THREAD

**Issue by uchechukwudim** [PaystackHQ/paystack-android#22]
So... I put in card details (Visa card) submit, it bring up some dialog to verify i suppose and then it closes by it self. Maybe I am implementing it the wrong way. Is there a working example i can use to see how to verify a visa card on paystack?

**Comment by ibrahimlawal** [comment]
Hey @uchechukwudim Kindly check the dashboard for the failure message. I also expect that once it closed, it would give you an Exception that shows why it did.

**Comment by uchechukwudim** [comment]
"The card holder was not authorised. This is used in 3-D Secure Authentication" That is the message i get on the dashboard and the message it bring back to me.

**Comment by uchechukwudim** [comment]
Have same issue with IOS too. maybe there is something i am doing wrong. That is why i ask for a working example to accept a visa card that need extra verification, to be sure.

**Comment by ibrahimlawal** [comment]
"The card holder was not authorised. This is used in 3-D Secure Authentication" is the message from the bank. If you try at a later time, it could possibly succeed.

**Comment by KingIdee** [comment]
When I insert the wrong PIN, the dialog closes. It should give three chances before closing.

**Comment by ibrahimlawal** [comment]
Ha @KingIdee we can't be an architect of woes. Card will be blocked after 3 incorrect PIN tries. Better for the user to decide whether they want to retry at all.

**Comment by KingIdee** [comment]
Lol.. okay
