### ISSUE TITLE
ExpiredAccessCodeException on all Verve test cards

### ISSUE THREAD

**Issue by ifiok** [PaystackHQ/paystack-android#27]
# Problem/Motivation
(Why the issue was filed, steps to reproduce the problem, etc.)
The card addition always throws an error of ExpiredAccessCodeException in the test environment.
I have gotten the access code from the http call to initiate a transaction from the server
Created a charge object like so:
```
@Override
    public void paystackAddCard(CreditCard card, String access_code) {
        Charge charge = new Charge();
        charge.setCard(new co.paystack.android.model.Card.Builder(
                card.getCardNumber(),
                card.getExpMonth(),
                card.getExpYear(),
                card.getSecurityCode()
        ).build());
        charge.setAccessCode(access_code);
        charge.setEmail(MyApplication.getUser().getEmail());
        view.callPaystackSdk(charge);

    }
```

## Repeatable
Specific conditions: Happens just on Verve test cards

(If it is a bug, you are reporting lease specify:)
**Bug**

## Steps to repeat
1. Get access code from server
2. Add card details in add card textfield ```5060 6666 6666 6666 666```
3. Add the CVV and expiry as stated in https://developers.paystack.co/v1.0/docs/test-cards
4. Call ```PaystackSdk.chargeCard```

## Expected Results:
Expected a success with transaction ID

## Actual Results:
Error! Please try again: a894ea34063d41fcacb6a9d617318d1393922c7c

**Comment by ibrahimlawal** [comment]
Hello PaystackHQ/paystack-android ,


I am out of office for a short leave. Please contact support@paystack.com .


Thanks!

**Comment by ifiok** [comment]
I just realized that this happens when there are spaces in the card numbers.
But then again, it works for VISA.

**Comment by ibrahimlawal** [comment]
@ifiok Oh, seen. perhaps a future update will remove all non-numeric characters before sending to the server
