### ISSUE TITLE
 Action not yet supported for mastercard by this app.

### ISSUE THREAD

**Issue by VISHNUTSATHEESH** [PaystackHQ/paystack-android#31]
# Android - Action not yet supported for mastercard by this app.

Facing issue in android  while performing credit card authentication in paystack using visa/master credit/debit cards

Caught co.paystack.android.exceptions.ChargeException: Action not yet supported for mastercard by this app.

**Comment by ibrahimlawal** [comment]
Please update your app to use the latest SDK version

-----Original Message-----
