### ISSUE TITLE
unable to charge VISA card

### ISSUE THREAD

**Issue by stonekase** [PaystackHQ/paystack-android#32]
# Problem

When charge card is called by the sdk,it takes me to a webview then it fails with the below error .
Also note that i use this same card for pos,uber etc.
I attached an image of me intercepting the transaction and you can see that the values where sent correctly---its a shame it wasnt encrypted when i decided to pull it.....

I had to manually mask the card details since i am sharing it here!!!!
![horridexperiece](https://user-images.githubusercontent.com/5037778/31851163-f16e038c-b657-11e7-96cf-a71aa9a6a23a.PNG)

"{"status":"error","message":"Transaction was blocked by the Payment Server because it did not pass all risk checks.","bank":"Access Bank"}"

## Proposed resolution
why must a webview be used?
My app would be better off with a straight forward implementation.

## Repeatable
Always

(If it is a bug, you are reporting lease specify:)

## Steps to repeat: (Describe how the issue can be repeated by someone who is to work on it)
just a normal transaction with a visa card.(i will also come up with the verve card issue aswell.)

## Expected Results:
Transaction should succeed or fail in a straight forward manner.
I had to dig too deep to find the issue,not good at all.

## Actual Results:
 I/System.out: what do we have here :: Transaction was blocked by the Payment Server because it did not pass all risk checks.
10-21 11:51:09.006 11138-11138/ng.com.sourcecard.aiki I/System.out: what do we have here22 :: {"status":"error","message":"Transaction was blocked by the Payment Server because it did not pass all risk checks.","bank":"Access Bank"}

**Comment by ibrahimlawal** [comment]
Hey Tim,

For your protection, our regulators have mandated that when we receive fresh card details for a charge, we must send it for bank authorization (webview or pin and otp). This is to avoid unauthorized usage.

The case you have reported is with regards to your Access Bank card. I would encourage that. The message means their payment server blocked the attempt. To resolve this, please send an email to your account officer for assistance. 

That you dug deep to get the error message is weird... All you have to do is handle the exception thrown by our SDK.

Hope that helps.

Thank you for choosing Paystack.

Thanks!

-----Original Message-----

**Comment by stonekase** [comment]
Hi Ibrahim,
Does this imply that every customer i have will have to write to his/her
bank?
I have 3 debit cards and two resolves to that while the verve is a whole
different story.

Regarding digging deep it is obvious you did not look at the image i
attached in my first post...you can instruct me on a simpler way to extract
those info because the sdk logs doesnt say much.

I use the card for uber and it works well.

**Comment by MohiniThakkar1995** [comment]
Hello,
With the visa card i'm not able to do the payment,
can someone please let me know what is wrong with the SDK, SDK is not working with Visa Card.
