### ISSUE TITLE
Compiling errors

### ISSUE THREAD

**Issue by contactolaolu44real** [PaystackHQ/paystack-android#33]
I am presently having five error integrating the dependency. Number one is this and what is the solution
Error:In <declare-styleable> ForegroundView, unable to find attribute foreground

**Comment by ibrahimlawal** [comment]
Hey @contactolaolu44real what version of Android Studio are you using?

Also please be sure to enable AAPT2

**Comment by contactolaolu44real** [comment]
I use version 3.0 and sure to have enabled AAPT 2

**Comment by ibrahimlawal** [comment]
Weird then. Please confirm you are also using the most recent build of our SDK (v3.0.9). If this fails, try v3.0.7

**Comment by ibrahimlawal** [comment]
In your `gradle.properties` file, please add the following line:

```
android.enableAapt2=true
```

**Comment by contactolaolu44real** [comment]
Ohh...thanks. Will now
Will get back

**Comment by contactolaolu44real** [comment]
i used sdk version 3.0.9 and the error continued

**Comment by ibrahimlawal** [comment]
Weird, you may need to restart your IDE (and/or clear your cache):

https://stackoverflow.com/questions/23025433/how-to-clear-gradle-cache

**Comment by contactolaolu44real** [comment]
Thanks....it has worked perfectly after effecting the changes

**Comment by ibrahimlawal** [comment]
Glad to be of assistance. Thank you for choosing Paystack!

**Comment by contactolaolu44real** [comment]
Please sir, what about cardinal look up failed exception

**Comment by ibrahimlawal** [comment]
@contactolaolu44real sounds like you were attempting payment with an invalid card in live mode.

**Comment by contactolaolu44real** [comment]
Thanks sir. Got the solution already. Was using live mode key for test cards details. Always grateful sir.

**Comment by aligorithm** [comment]
I have this same issue. I have tried the solutions and the issue still persists

**Comment by sagaya** [comment]
I also this same issue i am using v(3.0.9) of the SDK 

android studio 2.3.1 
gradle plugin 2.3.1
build tools 27.0.3

**Comment by jogboms** [comment]
@aligorithm @sagaya 
Create an `attrs.xml` file in the `values` directory

``` xml
<declare-styleable name="ForegroundView">
    <attr name="foreground" format="color" />
    <attr name="foregroundGravity" format="integer" />
    <attr name="foregroundInsidePadding" format="boolean" />
</declare-styleable>
```

**Comment by aligorithm** [comment]
I  have done that @jogboms and I still get the
```
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt
```
error

**Comment by aligorithm** [comment]
I have gotten rid of the error. I upgraded to the latest android studio and gradle, then updated all dependencies and installed the Paystack library.

**Comment by contactolaolu44real** [comment]
Please sir, android 4.2.2 api 17 does not open the payment authorization
page. What is the likely cause and remedy. Thanks as i wait to get your
response.

**Comment by ebukaprof** [comment]
Please i need help. I still see this error upgrading to paystack SDK 3.0.9. Even in 3.0.7.
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

**Comment by sirsheyi** [comment]
> Glad to be of assistance. Thank you for choosing Paystack!

Anyway one can solve the issue without having to upgrade Android studio?

**Comment by AdelekunAyoDeji** [comment]
Why did paystack fix minimumSdk at api16, its not good at all, while we are trying to also satisfying users with android 4.0 and above. Google console minimum api presently is api 14.

**Comment by neodavids** [comment]
> @aligorithm @sagaya
> Create an `attrs.xml` file in the `values` directory
> 
> ```
> <declare-styleable name="ForegroundView">
>     <attr name="foreground" format="color" />
>     <attr name="foregroundGravity" format="integer" />
>     <attr name="foregroundInsidePadding" format="boolean" />
> </declare-styleable>
> ```

this worked for me just now! thanks a lot

**Comment by Adebanji29** [comment]
AAPT: error: resource attr/foregroundGravity (aka com.stephen.CitiStackApp:attr/foregroundGravity) not found.
having this same error tried all the solutions above but still didnt work

**Comment by michael-paystack** [comment]
@Adebanji29 What version of the library are you using?

**Comment by peterchibunna** [comment]
I've included the attrs.xml file, and I'm still getting the errors above. I'm using gradle 6.2
