### ISSUE TITLE
SDK Does Not Validate Cards with PAN > 16 digits

### ISSUE THREAD

**Issue by steveamaza** [PaystackHQ/paystack-android#34]
# Problem/Motivation
When customer is trying to pay with a Verve card which is longer than 16 digits, SDK does not allow this.

## Proposed resolution
Update validation to accept Verve cards or other cards with PAN longer than 16 digits.

**Comment by ibrahimlawal** [comment]
This can only be untrue. The SDK doesn't even provide an input form. Have you tested and confirmed this bug? @steveamaza 

-----Original Message-----
