### ISSUE TITLE
Unable to install Library for Paystack:3.0.9

### ISSUE THREAD

**Issue by toluw** [PaystackHQ/paystack-android#39]
Each time I try to install Paystack:3.0.9 using the dependency: compile 'co.paystack.android:paystack:3.0.9' .
I am getting the error below:

Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt.

I am using android studio 2.3

**Comment by ibrahimlawal** [comment]
#33 may be related to your issue. Please check

**Comment by toluw** [comment]
Issue resolved. Thanks
