### ISSUE TITLE
Proguard rules

### ISSUE THREAD

**Issue by verygreenboi** [PaystackHQ/paystack-android#4]
Building with proguard enabled fails. How do I write proguard rules to solve this?

**Comment by ibrahimlawal** [comment]
Hi @verygreenboi, please endeavor to make sure that the delegate field of [TLSSocketFactory.java](https://github.com/PaystackHQ/paystack-android/blob/master/paystack/src/main/java/co/paystack/android/api/utils/TLSSocketFactory.java) is not renamed by proguard.
