### ISSUE TITLE
Is there any way to customize PinActivity and OtpActivity? 

### ISSUE THREAD

**Issue by borichellow** [PaystackHQ/paystack-android#40]
it's not an issue, but question. 

Case: when user add new card in our app, PaystackSdk request for pin/OTP (PinActivity/OtpActivity is run).
Obvious this inner activities are not in our app style. 
Is there any way to change it's layouts?

**Comment by ibrahimlawal** [comment]
No way yet.

However we are open to a PR that helps us expose the possibility to use a custom Activity to get the values.

**Comment by borichellow** [comment]
@ibrahimlawal can you provide some example, or docs how to do it?

**Comment by ibrahimlawal** [comment]
It can't be done yet.

**Comment by mikelis135** [comment]
How about you make your dialog finer, or give the ability to extend the style to tweak a few things of your inner activity.

**Comment by mikelis135** [comment]
You can give us access to parse say, our primary color, which you can use for the paystack dialog header background, instead of the static black, or create an interface we can implement to access your UI and teak thanks.

**Comment by stonekase** [comment]
this response might come late but the way I did mine was to use the GitHub source code and I changed the activity the pin/otp activity is called. with the source code you can pretty much do anything. for example you can hold off processing until verification timeout window to auto-verify etc etc

**Comment by stonekase** [comment]
> No way yet.
> 
> However we are open to a PR that helps us expose the possibility to use a custom Activity to get the values.

I did this over 1 year ago, with the source code one can pretty much do anything.the only thing is the person will have to manually update changes to the sdk if there is ever any breaking changes.so far so good my implementation still works.....

**Comment by mikelis135** [comment]
Yes, I have the source code. Last time I edited it, I broke it. 
I'll take my time to edit it and give it a cleaner design and make sure it's working

**Comment by stonekase** [comment]
> @ibrahimlawal can you provide some example, or docs how to do it?

<img width="1233" alt="screen shot 2018-09-19 at 7 35 51 pm" src="https://user-images.githubusercontent.com/5037778/45773942-9ac17300-bc43-11e8-985b-79e65ec1cfa3.png">

**Comment by stonekase** [comment]
> Yes, I have the source code. Last time I edited it, I broke it.
> I'll take my time to edit it and give it a cleaner design and make sure it's working

I just added some images to help show u the classes to modify.my implementation still works from 2015

**Comment by mikelis135** [comment]
Cool, thanks
