### ISSUE TITLE
Error: "Expected ':status' header not present" while processing CC payment.

### ISSUE THREAD

**Issue by ollorin** [PaystackHQ/paystack-android#44]
# Problem/Motivation
We faced an issue with PayStack integration into our Android app.
When we trying to make a payment using a credit card we see error "**Expected ':status' header not present**".

Processing of international Credit Cards is turned on for our account, we already processed several similar payments before.

SDK version used is 3.0.9

## Proposed resolution
Help needed.

## Repeatable
Always.
Appeared during last several days.

## Steps to repeat: (Describe how the issue can be repeated by someone who is to work on it)
1) We initialize a transaction at our backend, backend returns access_code - this is working without issues.
2) We collecting information about user's Credit Card in the application.
3) We using PayStack SDK's chargeCard function to process payment (with access_code and Credit Card information), but here we receiving an error "**Expected ':status' header not present**"

## Expected Results:
Expectation to have processed payment.

## Actual Results:
Error: "**Expected ':status' header not present**" while processing CC payment, in onError of function chargeCard.

**Comment by ollorin** [comment]
Issue was resolved by updating libraries in the android project.

**Comment by tecmie** [comment]
great, glad to see you worked it out
