### ISSUE TITLE
App crashes when trying to initiate transaction locally

### ISSUE THREAD

**Issue by mbmyke** [PaystackHQ/paystack-android#46]
# Problem/Motivation
When I try to initiate a transaction locally, the app crashes with the error "Could not find class 'co.paystack.android.TransactionManager$1', referenced from method co.paystack.android.TransactionManager."  My android studio version is 3.0.

**Comment by mbmyke** [comment]
Thanks Ibrahim. I have updated my android studio and now using `co.paystack.android:paystack:3.0.10` but I am still getting the error. The error occurs when this is called: `  PaystackSdk.chargeCard(Payment.this, charge, new Paystack.TransactionCallback().....` Please why is the class `'co.paystack.android.TransactionManager` not found?

**Comment by ibrahimlawal** [comment]
Awesome. Glad that's resolved boss

-----Original Message-----
