### ISSUE TITLE
Paystack Transaction Amount Conversion

### ISSUE THREAD

**Issue by AdityaLabhade** [PaystackHQ/paystack-android#47]
We have successfully integrated Paystack sdk in Web, Android and iOS application. We are able to do successful transactions also. But we are getting one problem during transactions is that when we are sending the transaction amount it is getting divided by 100 for Nigerian currency ( Naira )

eg.	
If we assign transaction amount as 3500 /-
then it is converted to 35 ₦ 

How to solve this? Any help will be appreciated.

**Comment by steveamaza** [comment]
Hello @AdityaLabhade , the documentation states that amount is sent in kobo. If you do not convert it to naira by first multiplying it by 100, what you are effectively doing is sending 3500 kobo which is equal to N35. Please close this issue as it is not a bug and instead multiply your values by 100 before passing it on to the API.

**Comment by AdityaLabhade** [comment]
Solved my problem,
Thank you..

**Comment by IDFDeveloper** [comment]
I have successfully integration the **PayStack** in android platform. How to pass 1500.50 INR amount using it. I have checked in the **PayStack** SDK that **Charge.setAmount** is supported only Integer value. When I pass 1000 or something like that kind of amount which is not contain any fraction value then it working fine.

**Comment by steveamaza** [comment]
Hi @IDFDeveloper, in that case, pass 150050. The currency is passed in the subunit of the currency, not the main unit

**Comment by IDFDeveloper** [comment]
@steveamaza Thank you so much for your reply.
