### ISSUE TITLE
Adding meta data to Charge

### ISSUE THREAD

**Issue by larikraun** [PaystackHQ/paystack-android#5]
# Problem

I can't currently add meta data to Charge details.
# Proposed Solution

charge.setKey("key","value");
# Usage

charge.setKey("cartId","123abc");

**Comment by ibrahimlawal** [comment]
Thanks. This is noted. We will add this function to the library.

**Comment by ibrahimlawal** [comment]
@larikraun `charge.putMetadata` and `charge.putCustomField` have been added to provide the functionality you requested. Thanks!

**Comment by larikraun** [comment]
@ibrahimlawal Thanks. I will do.

**Comment by larikraun** [comment]
@ibrahimlawal Tested OK .
