### ISSUE TITLE
**createToken method not found anymore** I need to send a token to the server as usually done with PaystackSdk.createToken(card, new Paystack.TokenCallback() { @Override public void onCreate(Token token) {}  I guess it has been deprecated. Please is there a workaround for this?

### ISSUE THREAD

**Issue by obyslink** [PaystackHQ/paystack-android#51]
# Problem/Motivation
(Why the issue was filed, steps to reproduce the problem, etc.)

## Proposed resolution
(Description of the proposed solution, the rationale behind it, and workarounds for people who cannot use the patch.)

## Repeatable
Always|Sometimes|Specific conditions|Specific times

(If it is a bug, you are reporting lease specify:)

## Steps to repeat: (Describe how the issue can be repeated by someone who is to work on it)
1. Step 1
2. Step 2
3. ...

## Expected Results:
(What you expected steps 1, 2 and 3 to give)

## Actual Results:
(What is gave including any error messages, memory dump etc that can help)

**Comment by obyslink** [comment]
**createToken method not found anymore** 

I need to send a token to the server as usually done with PaystackSdk.createToken(card, new Paystack.TokenCallback() { @Override public void onCreate(Token token) {}
 ## I guess it has been deprecated. Please is there a workaround for this?

**Comment by steveamaza** [comment]
@obyslink please edit this issue by filling in the fields in the template so we can understand this problem better and help

**Comment by ibrahimlawal** [comment]
> I guess it has been deprecated. Please is there a workaround for this?

no workaround
