### ISSUE TITLE
 co.paystack.android.exceptions.PaystackSdkNotInitializedException: Paystack SDK has not been initialized.The SDK has to be initialized before use

### ISSUE THREAD

**Issue by chuksdsilent** [PaystackHQ/paystack-android#54]
I get this error on my page when I try the run my application

**Comment by ibrahimlawal** [comment]
@chuksdsilent there is an existing fixed issue with same description. Kindly see the fix and reopen the issue if it didn't work for you.

**Comment by chuksdsilent** [comment]
okay it worked for me
