### ISSUE TITLE
I dont want my customers to enter card details within my app. Is there a payment page which does not contain firstname and lastname spaces Just card details only? 

### ISSUE THREAD

**Issue by lekeCoder** [PaystackHQ/paystack-android#56]
# Problem/Motivation
(Why the issue was filed, steps to reproduce the problem, etc.)

## Proposed resolution
(Description of the proposed solution, the rationale behind it, and workarounds for people who cannot use the patch.)

## Repeatable
Always|Sometimes|Specific conditions|Specific times

(If it is a bug, you are reporting lease specify:)

## Steps to repeat: (Describe how the issue can be repeated by someone who is to work on it)
1. Step 1
2. Step 2
3. ...

## Expected Results:
(What you expected steps 1, 2 and 3 to give)

## Actual Results:
(What is gave including any error messages, memory dump etc that can help)

**Comment by michael-paystack** [comment]
Hi,
I'm closing this now because it's been dormant for two years.
Please open a new issue if this still needs to be addressed.
