### ISSUE TITLE
Standard integration of authorization url with webview

### ISSUE THREAD

**Issue by ebukaprof** [PaystackHQ/paystack-android#57]
Please i need urgent help.

How do i do standard integration of payment authorization url with webview in native android app? 
I want to take advantage of "Pay With Bank".

**Comment by steveamaza** [comment]
@ebukaprof, To implement Pay With Bank, you don't need a webview. Use the Paystack API instead. See documentation at https://developers.paystack.co/v2.0/docs/charging-a-bank-account

**Comment by ebukaprof** [comment]
@steveamaza Thanks a lot. 
Apart from Pay with Bank, Paystack payment authorization URL comes with total package. How do i integrate with webview. I wouldn't want to deal with android SDK in other to collect card details.

**Comment by steveamaza** [comment]
Hey @ebukaprof sorry for the late response. You could open the authorization_url right on a webpage then. Tried that yet?

**Comment by ebukaprof** [comment]
@steveamaza How can i open it using webview? Because it doesn't seem to be opening on webview whereas other web url including paystack.com opens on webview.

**Comment by afomic** [comment]
i was able to open it on a webview, but the webhook URL is not getting triggered after a successful transaction

**Comment by michael-paystack** [comment]
Hello,
I'm closing this issue because it's been dormant for a while.
Please open a new issue if this still needs to be addressed.
Thanks
