### ISSUE TITLE
Android API Error

### ISSUE THREAD

**Issue by NGDigitals** [PaystackHQ/paystack-android#61]
I integrated paystack into my android project several months ago and every thing works fine until recently when I started getting charge exception with error message: 
	Error! Please try again

I have used different media in the past days to contact your support department, but have not gotten any response. Please this is urgent and quick response will really be appreciated.

Thank you

**Comment by sureshseenis** [comment]
Charge Exemption Amount Inconsistency

**Comment by steveamaza** [comment]
@sureshseenis what amount are you sending?

**Comment by NGDigitals** [comment]
Issue has been resolved
