### ISSUE TITLE
How to get Subscription Code

### ISSUE THREAD

**Issue by wedowebapps** [PaystackHQ/paystack-android#65]
Hey,

I need your help ASAP. We have followed all your steps and set up with our Android Code and getting successful transaction but our concern is how we can get Subscription code like [SUB_2x0unvifdsizele] in response. We are getting that code in email.

Because in the Successful response of transaction.getReference(); we are getting reference code but when we execute the Verifying Transaction Method with reference number we are not getting any field which provides Subscription Code that we store in our database and use at the time of Cancel or Disable Subscription.

So can you please you with this so we can complete the things ASAP.

Please let me know if you need any further details.

Regards;
Pratik

**Comment by steveamaza** [comment]
Hi Pratik,

Apologies for catching this so late. The best way to get the plan details is to listen for the [invoice.update event[(https://developers.paystack.co/v1.0/docs/events#section-structure-of-an-event-object) on your webhook URL

@wedowebapps
