### ISSUE TITLE
Payment transaction issue

### ISSUE THREAD

**Issue by gagan50** [PaystackHQ/paystack-android#66]
Declined. Please use the test card since you are doing a test transaction.
i'm using test card credentials that are mentioned below but it throw error

5438898014560229
cvv 564
Expiry: 10/20
Pin 3310
otp 12345

**Comment by steveamaza** [comment]
@gagan50 that's not a test card. FInd the test cards at https://developers.paystack.co/v2.0/docs/test-cards

**Comment by gagan50** [comment]
ok thanks

**Comment by gagan50** [comment]
now its showing error
Please try again

**Comment by gagan50** [comment]
String cardNumber = "5060 6666 6666 6666 666";
        int expiryMonth = 10; //any month in the future
        int expiryYear = 22; // any year in the future. '2018' would work also!
        String cvv = "123";  // cvv of the test card

**Comment by ellu15** [comment]
getting same error "Please try again"
for all testing Verve cards.

**Comment by steveamaza** [comment]
@ellu15 what's the transaction reference so I can check? or the email address used

**Comment by LuomyEQua** [comment]
@steveamaza i used my personal email address and it keeps telling me "Invalid Email Address Passed"

**Comment by michael-paystack** [comment]
Hello,
I'm closing this issue because it's been dormant for a while.
Please open a new issue if this still needs to be addressed.
Thanks

**Comment by sterlingking1990** [comment]
If you still experience "invalid email address passed" check that you have charge.setEmail("customer_email@abc.com")  when setting up the charge object. This solved it for me
