### ISSUE TITLE
Unable to resolve host "standard.paystack.co": No address associated with hostname

### ISSUE THREAD

**Issue by ray86** [PaystackHQ/paystack-android#68]
Hv been tryin paystack with test cards and was working properly.

Just started having this issue below

Unable to resolve host "standard.paystack.co": No address associated with hostname

**Comment by steveamaza** [comment]
@ray86 have you enabled internet permissions for the app? As specified in https://github.com/PaystackHQ/paystack-android#0-prepare-for-use? If yes, then check your internet connection

**Comment by ray86** [comment]
it wasnt internet permission issues and not from my internet connection either. it was working properly and then it started throwing that error when i call charge card.  Though the issue resolved on its own after some time.
