### ISSUE TITLE
SDK installing error

### ISSUE THREAD

**Issue by Cob007** [PaystackHQ/paystack-android#69]
![Screenshot from 2019-05-08 11-58-15](https://user-images.githubusercontent.com/21246764/57370721-b5236f00-7188-11e9-9758-6468bdb6c9af.png)
# Problem/Motivation
SDK installation error

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve co.paystack.android:paystack:3.0.11.
Open File
Show Details

Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve co.paystack.android:paystack:3.0.11.
Open File
Show Details

Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve co.paystack.android:paystack:3.0.11.
Open File
Show Details

Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve co.paystack.android:paystack:3.0.11.
Open File
Show Details

Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve co.paystack.android:paystack:3.0.11.
Open File
Show Details

**Comment by ibrahimlawal** [comment]
You are attempting to install a version we are yet to release. Latest version is `3.0.10`

**Comment by ibrahimlawal** [comment]
Apologies, just found 3.0.11 listed on bintray

**Comment by ibrahimlawal** [comment]
Most times I hit this issue, restarting Android Studio helps.

**Comment by ibrahimlawal** [comment]
However, if this fails, kindly try using v3.0.10

**Comment by Cob007** [comment]
@ibrahimlawal I have tried installing that version and I encountered same error

**Comment by ibrahimlawal** [comment]
@Cob007 wow

may I see your repositories gradle setting? As a last resort, you can add our bintray as a maven source.

```
repositories {
    maven {
        url  "https://dl.bintray.com/paystack/maven" 
    }
}
```

**Comment by ibrahimlawal** [comment]
PS: we released a v3.0.12 with upgraded dependencies on the 8th of May. Do try it out.

**Comment by Cob007** [comment]
Android resource linking failed
Output:  /home/michealcob/.gradle/caches/transforms-1/files-1.1/jetified-paystack-3.0.12.aar/14333014c7c9bd34f17613a6c397c712/res/layout/co_paystack_android____activity_otp.xml:16: error: attribute auto_submit (aka michealcob.folktalescloud:auto_submit) not found.
/home/michealcob/.gradle/caches/transforms-1/files-1.1/jetified-paystack-3.0.12.aar/14333014c7c9bd34f17613a6c397c712/res/layout/co_paystack_android____activity_otp.xml:16: error: attribute button_alpha_textsize (aka michealcob.folktalescloud:button_alpha_textsize) not found.
/home/michealcob/.gradle/caches/transforms-1/files-1.1/jetified-paystack-3.0.12.aar/14333014c7c9bd34f17613a6c397c712/res/layout/co_paystack_android____activity_otp.xml:16: error: attribute button_drawable_size (aka michealcob.folktalescloud:button_drawable_size) not found.
/home/michealcob/.gradle/caches/transforms-1/files-1.1/jetified-paystack-3.0.12.aar/14333014c7c9bd34f17613a6c397c712/res/layout/co_paystack_android____activity_otp.xml:16: error: attribute button_numeric_textsize (aka michealcob.folktalescloud:button_numeric_textsize) not found.
/home/michealcob/.gradle/caches/transforms-1/files-1.1/jetified-paystack-3.0.12.aar/14333014c7c9bd34f17613a6c397c712/res/layout/co_paystack_android____activity_otp.xml:16: error: attribute pin_indicator_stroke_width (aka michealcob.folktalescloud:pin_indicator_stroke_width) not found.
/home/michealcob/.gradle/caches/transforms-1/files-1.1/jetified-paystack-3.0.12.aar/14333014c7c9bd34f17613a6c397c712/res/layout/co_paystack_android____activity_otp.xml:16: error: attribute pin_length (aka michealcob.folktalescloud:pin_length) not found.
/home/michealcob/.gradle/caches/transforms-1/files-1.1/jetified-paystack-3.0.12.aar/14333014c7c9bd34f17613a6c397c712/res/layout/co_paystack_android____activity_otp.xml:16: error: attribute place_digits_randomly (aka michealcob.folktalescloud:place_digits_randomly) not found.
/home/michealcob/.gradle/caches/transforms-1/files-1.1/jetified-paystack-3.0.12.aar/14333014c7c9bd34f17613a6c397c712/res/layout/co_paystack_android____activity_otp.xml:16: error: attribute prompt_text (aka michealcob.folktalescloud:prompt_text) not found.
/home/michealcob/.gradle/caches/transforms-1/files-1.1/jetified-paystack-3.0.12.aar/14333014c7c9bd34f17613a6c397c712/res/layout/co_paystack_android____activity_otp.xml:16: error: attribute prompt_textsize (aka michealcob.folktalescloud:prompt_textsize) not found.
/home/michealcob/.gradle/caches/transforms-1/files-1.1/jetified-paystack-3.0.12.aar/14333014c7c9bd34f17613a6c397c712/res/layout/co_paystack_android____activity_otp.xml:16: error: attribute vibrate_on_incomplete_submit (aka michealcob.folktalescloud:vibrate_on_incomplete_submit) not found.
/home/michealcob/.gradle/caches/transforms-1/files-1.1/jetified-paystack-3.0.12.aar/14333014c7c9bd34f17613a6c397c712/res/layout/co_paystack_android____activity_pin.xml:17: error: attribute button_alpha_textsize (aka michealcob.folktalescloud:button_alpha_textsize) not found.
/home/michealcob/.gradle/caches/transforms-1/files-1.1/jetified-paystack-3.0.12.aar/14333014c7c9bd34f17613a6c397c712/res/layout/co_paystack_android____activity_pin.xml:17: error: attribute button_drawable_size (aka michealcob.folktalescloud:button_drawable_size) not found.
/home/michealcob/.gradle/caches/transforms-1/files-1.1/jetified-paystack-3.0.12.aar/14333014c7c9bd34f17613a6c397c712/res/layout/co_paystack_android____activity_pin.xml:17: error: attribute button_numeric_textsize (aka michealcob.folktalescloud:button_numeric_textsize) not found.
/home/michealcob/.gradle/caches/transforms-1/files-1.1/jetified-paystack-3.0.12.aar/14333014c7c9bd34f17613a6c397c712/res/layout/co_paystack_android____activity_pin.xml:17: error: attribute pin_indicator_size (aka michealcob.folktalescloud:pin_indicator_size) not found.
/home/michealcob/.gradle/caches/transforms-1/files-1.1/jetified-paystack-3.0.12.aar/14333014c7c9bd34f17613a6c397c712/res/layout/co_paystack_android____activity_pin.xml:17: error: attribute pin_indicator_spacing (aka michealcob.folktalescloud:pin_indicator_spacing) not found.
/home/michealcob/.gradle/caches/transforms-1/files-1.1/jetified-paystack-3.0.12.aar/14333014c7c9bd34f17613a6c397c712/res/layout/co_paystack_android____activity_pin.xml:17: error: attribute pin_indicator_stroke_width (aka michealcob.folktalescloud:pin_indicator_stroke_width) not found.
/home/michealcob/.gradle/caches/transforms-1/files-1.1/jetified-paystack-3.0.12.aar/14333014c7c9bd34f17613a6c397c712/res/layout/co_paystack_android____activity_pin.xml:17: error: attribute pin_length (aka michealcob.folktalescloud:pin_length) not found.
/home/michealcob/.gradle/caches/transforms-1/files-1.1/jetified-paystack-3.0.12.aar/14333014c7c9bd34f17613a6c397c712/res/layout/co_paystack_android____activity_pin.xml:17: error: attribute prompt_text (aka michealcob.folktalescloud:prompt_text) not found.
/home/michealcob/.gradle/caches/transforms-1/files-1.1/jetified-paystack-3.0.12.aar/14333014c7c9bd34f17613a6c397c712/res/layout/co_paystack_android____activity_pin.xml:17: error: attribute prompt_textsize (aka michealcob.folktalescloud:prompt_textsize) not found.
error: failed linking file resources.

**Comment by Cob007** [comment]
@ibrahimlawal I have tried to the invalidate cache

**Comment by Cob007** [comment]
I have tried to the invalidate cache

**Comment by Cob007** [comment]
I have tried to the invalidate cache

**Comment by Cob007** [comment]
After Upgrading my android studio, I was able to install your sdk but on "project build" I was returned back to the error 
Android resource linking failed
/home/michealcob/.gradle/caches/transforms-2/files-2.1/4114dade4e7e5650418fbe225a84f4f6/res/layout/co_paystack_android____activity_otp.xml:16: error: attribute auto_submit (aka michealcob.folktalescloud:auto_submit) not found.
/home/michealcob/.gradle/caches/transforms-2/files-2.1/4114dade4e7e5650418fbe225a84f4f6/res/layout/co_paystack_android____activity_otp.xml:16: error: attribute button_alpha_textsize (aka michealcob.folktalescloud:button_alpha_textsize) not found.
/home/michealcob/.gradle/caches/transforms-2/files-2.1/4114dade4e7e5650418fbe225a84f4f6/res/layout/co_paystack_android____activity_otp.xml:16: error: attribute button_drawable_size (aka michealcob.folktalescloud:button_drawable_size) not found.
/home/michealcob/.gradle/caches/transforms-2/files-2.1/4114dade4e7e5650418fbe225a84f4f6/res/layout/co_paystack_android____activity_otp.xml:16: error: attribute button_numeric_textsize (aka michealcob.folktalescloud:button_numeric_textsize) not found.
/home/michealcob/.gradle/caches/transforms-2/files-2.1/4114dade4e7e5650418fbe225a84f4f6/res/layout/co_paystack_android____activity_otp.xml:16: error: attribute pin_indicator_stroke_width (aka michealcob.folktalescloud:pin_indicator_stroke_width) not found.
/home/michealcob/.gradle/caches/transforms-2/files-2.1/4114dade4e7e5650418fbe225a84f4f6/res/layout/co_paystack_android____activity_otp.xml:16: error: attribute pin_length (aka michealcob.folktalescloud:pin_length) not found.
/home/michealcob/.gradle/caches/transforms-2/files-2.1/4114dade4e7e5650418fbe225a84f4f6/res/layout/co_paystack_android____activity_otp.xml:16: error: attribute place_digits_randomly (aka michealcob.folktalescloud:place_digits_randomly) not found.
/home/michealcob/.gradle/caches/transforms-2/files-2.1/4114dade4e7e5650418fbe225a84f4f6/res/layout/co_paystack_android____activity_otp.xml:16: error: attribute prompt_text (aka michealcob.folktalescloud:prompt_text) not found.
/home/michealcob/.gradle/caches/transforms-2/files-2.1/4114dade4e7e5650418fbe225a84f4f6/res/layout/co_paystack_android____activity_otp.xml:16: error: attribute prompt_textsize (aka michealcob.folktalescloud:prompt_textsize) not found.
/home/michealcob/.gradle/caches/transforms-2/files-2.1/4114dade4e7e5650418fbe225a84f4f6/res/layout/co_paystack_android____activity_otp.xml:16: error: attribute vibrate_on_incomplete_submit (aka michealcob.folktalescloud:vibrate_on_incomplete_submit) not found.
/home/michealcob/.gradle/caches/transforms-2/files-2.1/4114dade4e7e5650418fbe225a84f4f6/res/layout/co_paystack_android____activity_pin.xml:17: error: attribute button_alpha_textsize (aka michealcob.folktalescloud:button_alpha_textsize) not found.
/home/michealcob/.gradle/caches/transforms-2/files-2.1/4114dade4e7e5650418fbe225a84f4f6/res/layout/co_paystack_android____activity_pin.xml:17: error: attribute button_drawable_size (aka michealcob.folktalescloud:button_drawable_size) not found.
/home/michealcob/.gradle/caches/transforms-2/files-2.1/4114dade4e7e5650418fbe225a84f4f6/res/layout/co_paystack_android____activity_pin.xml:17: error: attribute button_numeric_textsize (aka michealcob.folktalescloud:button_numeric_textsize) not found.
/home/michealcob/.gradle/caches/transforms-2/files-2.1/4114dade4e7e5650418fbe225a84f4f6/res/layout/co_paystack_android____activity_pin.xml:17: error: attribute pin_indicator_size (aka michealcob.folktalescloud:pin_indicator_size) not found.
/home/michealcob/.gradle/caches/transforms-2/files-2.1/4114dade4e7e5650418fbe225a84f4f6/res/layout/co_paystack_android____activity_pin.xml:17: error: attribute pin_indicator_spacing (aka michealcob.folktalescloud:pin_indicator_spacing) not found.
/home/michealcob/.gradle/caches/transforms-2/files-2.1/4114dade4e7e5650418fbe225a84f4f6/res/layout/co_paystack_android____activity_pin.xml:17: error: attribute pin_indicator_stroke_width (aka michealcob.folktalescloud:pin_indicator_stroke_width) not found.
/home/michealcob/.gradle/caches/transforms-2/files-2.1/4114dade4e7e5650418fbe225a84f4f6/res/layout/co_paystack_android____activity_pin.xml:17: error: attribute pin_length (aka michealcob.folktalescloud:pin_length) not found.
/home/michealcob/.gradle/caches/transforms-2/files-2.1/4114dade4e7e5650418fbe225a84f4f6/res/layout/co_paystack_android____activity_pin.xml:17: error: attribute prompt_text (aka michealcob.folktalescloud:prompt_text) not found.
/home/michealcob/.gradle/caches/transforms-2/files-2.1/4114dade4e7e5650418fbe225a84f4f6/res/layout/co_paystack_android____activity_pin.xml:17: error: attribute prompt_textsize (aka michealcob.folktalescloud:prompt_textsize) not found.
error: failed linking file resources.

![Screenshot from 2019-05-17 08-48-28](https://user-images.githubusercontent.com/21246764/57911768-90ae4d80-7880-11e9-93b1-cc098ba606f5.png)

**Comment by Cob007** [comment]
@ibrahimlawal  please can you attend to this urgently

**Comment by ibrahimlawal** [comment]
Weird.... apologies for the tardy response. Are you available for a screen share soon? Also, you may want to run updates on your IDE... I see a prompt for updates

**Comment by othreecodes** [comment]
<img width="1307" alt="Screenshot 2019-05-27 at 2 58 50 PM" src="https://user-images.githubusercontent.com/18391371/58424729-fa540600-808f-11e9-9bd1-10a7dccf382d.png">
Getting the same Issue here with *v3.0.12*

**Comment by knightbenax** [comment]
This is still very much happening 
![Screenshot 2019-06-05 at 6 57 20 PM](https://user-images.githubusercontent.com/3107111/58978474-caa9aa00-87c3-11e9-9918-4312c81098ee.png)

**Comment by Presheda** [comment]
@ibrahimlawal 
am still getting the same error 
![Screenshot (2)](https://user-images.githubusercontent.com/26353504/62178126-ad1a3c00-b33f-11e9-8f11-130ed6066709.png)

**Comment by Presheda** [comment]
> @ibrahimlawal
> am still getting the same error
> ![Screenshot (2)](https://user-images.githubusercontent.com/26353504/62178126-ad1a3c00-b33f-11e9-8f11-130ed6066709.png)

if you are getting the error above, its because there is another dependency the SDK is using that was not mentioned in the documentation. the name of the library is **co.paystack.android.design.widget.PinPadView**

to fix this error simply add 
**implementation 'co.paystack.android.design.widget:pinpad:1.0.1'** to your build.gradle file.

here is the link for updates and reference 
https://github.com/PaystackHQ/library-android-pinpad

**Comment by ibrahimlawal** [comment]
Sweeeet!!! @knightbenax @othreecodes @Cob007 Did doing the above resolve the issue for you?
