### ISSUE TITLE
How to Tokenize a card

### ISSUE THREAD

**Issue by Asendo316** [PaystackHQ/paystack-android#70]
I have tried this 
`        PaystackSdk.createToken(card, new Paystack.TokenCallback() {
              @Override
              public void onCreate(Token token) {
                  if(token != null) {
                      //TODO dismiss progress

                      //send the token to your server for charging
                  }
              }

              @Override
              public void onError(Exception error) {
                  //dismiss progress, show error to the user
              }
          });
      }`

But createToken no longer exists in the SDK

**Comment by ibrahimlawal** [comment]
Yes it has been discontinued. Please use `chargeCard` as documented.
