### ISSUE TITLE
How do I set amount for dollar transactions

### ISSUE THREAD

**Issue by bennyspark** [PaystackHQ/paystack-android#71]
I understand that the amount field in the Paystack android sdk is set in kobo. I want to add dollar transactions for my app such that people can make payments in dollar currency. Is this possible with Paystack? How would it work?

**Comment by ibrahimlawal** [comment]
@bennyspark You set it in cents.

**Comment by bennyspark** [comment]
how do I do that? its not stated in the documentation

**Comment by ibrahimlawal** [comment]
If you want 10 naira, you send amount in kobo... 10*100 = 1000 kobo

If you  want 10 dollars, you send amount in cents... 10*100 = 1000 cents

currency in the first case would be `NGN`, in the second case `USD`
