### ISSUE TITLE
Cannot resolve callback 

### ISSUE THREAD

**Issue by SteveOye** [PaystackHQ/paystack-android#79]
@ibrahimlawal 
screenshot of error on the logcat 
![error1](https://user-images.githubusercontent.com/39436388/65738180-e4576000-e0d8-11e9-85a9-03b8765536b8.png)

![error2](https://user-images.githubusercontent.com/39436388/65738194-f46f3f80-e0d8-11e9-87d2-8b3b6278f440.png)

# Problem/Motivation
The transaction call back keeps on given an error 
java.lang.NoClassDefFoundError: co.paystack.android.TransactionManager$1

Library source does not match the bytecode for class TransactionManager

## Proposed resolution
Error comes from the line where chargeCard() is called to the PaystackSdk, it seems theirs a missing import of files or something...

 PaystackSdk.chargeCard(MainActivity.this, charge, new Paystack.TransactionCallback()  

## Repeatable
Always

## Steps to repeat: (Describe how the issue can be repeated by someone who is to work on it)
run a build on this 
https://github.com/SteveOye/PaystackAndroid

## Expected Results:
Successful Transaction

## Result
App crashes

**Comment by michael-paystack** [comment]
Hello,
This issue should be solved in newer versions of the SDK.
I'm closing this issue because it's been dormant for a while.
Please open a new issue if this still needs to be addressed.
Thanks
