### ISSUE TITLE
transaction.card.authenticate is not a function 

### ISSUE THREAD

**Issue by femotizo** [PaystackHQ/paystack-android#80]
### Good day, i am stuck while using paystack.js v2 .

Uncaught (in promise) TypeError: transaction.card.authenticate is not a function at submitFunction  after switching to Live mode while using "Building your checkout form" v2 doc at https://developers.paystack.co/v2.0/docs/paystack-custom

find below the information from my chrome dev tools.

#### var validation = Paystack.Card.validate(card);
{"isValid":true,"result":{"number":true,"expiry":true,"cvv":true}}

#### var chargeResponse = await transaction.chargeCard();
{"status":"auth","message":"Please send PIN","data":{"auth":"pin"}}

#### const authenticationResponse = await transaction.card.authenticate(token);
_Uncaught (in promise) TypeError: transaction.card.authenticate is not a function at submitFunction_ 

Thank you.

**Comment by steveamaza** [comment]
Hey @femotizo. Any reason you're not using the SDK instead? Paystack JS is still in beta and not the best experience on Android

**Comment by femotizo** [comment]
Thank you @steveamaza, i was working on the web environment not Android.

can you suggest any other method / doc i can use to **build custom checkout form**.

**Comment by steveamaza** [comment]
Hi @femotizo, Paystack JS is still in beta so a lot keeps changing. Please send us a message on Payslack at https://slack.paystack.com so we can assist
