### ISSUE TITLE
Pay into an account incase of a refund when bank details is available.

### ISSUE THREAD

**Issue by Xy-joe** [PaystackHQ/paystack-android#81]
# Apart from charging a caro 
I'm requesting account details from users. In case if a refund, is there a way to use the paystack androidsdk to pay into another account rather than bill the card. Card details is for billing while the bank details will be for depositing. Is there a way to achieve this on The paystack android api

**Comment by steveamaza** [comment]
Hi @Xy-joe, no there's no way to use the SDK to make a payment into a bank account. However, you can use our API to do this directly https://developers.paystack.co/docs/funds-transfers.

This isn't an issue (bug) so I'll be closing. You can contact our support team at hello@paystack.com if you need further help
