### ISSUE TITLE
How to initiate transfer

### ISSUE THREAD

**Issue by Yczar** [PaystackHQ/paystack-android#84]
Please how do I initiate transfer on Android studio with paystack... I mean paying my customers

**Comment by ibrahimlawal-paystack** [comment]
> Please how do I initiate transfer on Android studio with paystack... I mean paying my customers

You don't do that from an app. You secret key is required, and your secret key shoul donly be on your server.

What you can do is have an endpoint on your server through which the app can request a transfer for the authenticated user.

Hope that helps!

**Comment by Yczar** [comment]
> > Please how do I initiate transfer on Android studio with paystack... I mean paying my customers
> 
> You don't do that from an app. You secret key is required, and your secret key shoul donly be on your server.
> 
> What you can do is have an endpoint on your server through which the app can request a transfer for the authenticated user.
> 
> Hope that helps!

Can I drop my WhatsApp number I have more questions for u .... Please

**Comment by steveamaza** [comment]
Hello @Yczar, you can reach out to support@paystack.com if you have more issues and we'll gladly help you with this
