### ISSUE TITLE
Pay With Bank Feature

### ISSUE THREAD

**Issue by deLTreeTech** [PaystackHQ/paystack-android#86]
I have implemented paystack for android many times. Thank you guys for keeping it simple.

Can you please add Pay With Bank feature to the library. It will make our clients pay more than we have now. Thanks

**Comment by steveamaza** [comment]
You're welcome, @deLTreeTech. Your feedback has been noted. At the moment, however, you can implement pay with bank on your Android app by using the API. Here's the documentation - https://developers.paystack.co/v2.0/docs/charging-a-bank-account.
