### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Ochornma** [PaystackHQ/paystack-android#87]
I am getting this error
java.lang.NoClassDefFoundError: co.paystack.android.TransactionManager$1

**Comment by azeeza32** [comment]
> I am getting this error
> java.lang.NoClassDefFoundError: co.paystack.android.TransactionManager$1

Getting the same error here

**Comment by azeeza32** [comment]
> I am getting this error
> java.lang.NoClassDefFoundError: co.paystack.android.TransactionManager$1

I got the solution just add the following to your dependencies:
implementation 'com.squareup.retrofit2:retrofit:2.6.2'
implementation 'com.squareup.retrofit2:converter-gson:2.6.2'

**Comment by michael-paystack** [comment]
Hello,
This issue shouldn't exist in newer versions of the SDK.
I'll be closing this now. Please open a new issue if this still needs to be addressed.
Thanks
