### ISSUE TITLE
retrofit error          PaystackSdk.chargeCard(PaystackActivity.this, charge, new Paystack.TransactionCallback()  {   No virtual method sslSocketFactory(Ljavax/net/ssl/SSLSocketFactory;Ljavax/net/ssl/X509TrustManager;)Lokhttp3/OkHttpClient$Builder; in class Lokhttp3/OkHttpClient$Builder; or its super classes (declaration of 'okhttp3.OkHttpClient$Builder' appears in /data/app/com.fixy.user-nyiiUUG5NbqxYLp8Hm7UIg==/base.apk!classes3.dex)         at co.paystack.android.api.ApiClient.<init>(ApiClient.java:59)         at co.paystack.android.TransactionManager.initiate(TransactionManager.java:91)         at co.paystack.android.TransactionManager.chargeCard(TransactionManager.java:105)         at co.paystack.android.Paystack.chargeCard(Paystack.java:69)         at co.paystack.android.Paystack.chargeCard(Paystack.java:57)         at co.paystack.android.PaystackSdk.chargeCard(PaystackSdk.java:151)         at com.fixy.user.Activities.PaystackActivity.chargeCard(PaystackActivity.java:195)

### ISSUE THREAD

**Issue by ankush10abc** [PaystackHQ/paystack-android#88]
# Problem/Motivation
(Why the issue was filed, steps to reproduce the problem, etc.)

## Proposed resolution
(Description of the proposed solution, the rationale behind it, and workarounds for people who cannot use the patch.)

## Repeatable
Always|Sometimes|Specific conditions|Specific times

(If it is a bug, you are reporting lease specify:)

## Steps to repeat: (Describe how the issue can be repeated by someone who is to work on it)
1. Step 1
2. Step 2
3. ...

## Expected Results:
(What you expected steps 1, 2 and 3 to give)

## Actual Results:
(What is gave including any error messages, memory dump etc that can help)

**Comment by ankush7828333449** [comment]
No virtual method sslSocketFactory(Ljavax/net/ssl/SSLSocketFactory;Ljavax/net/ssl/X509TrustManager;)Lokhttp3/OkHttpClient$Builder; in class Lokhttp3/OkHttpClient$Builder; or its super classes (declaration of 'okhttp3.OkHttpClient$Builder' appears in /data/app/com.fixy.user-nyiiUUG5NbqxYLp8Hm7UIg==/base.apk!classes3.dex)
        at co.paystack.android.api.ApiClient.<init>(ApiClient.java:59)
        at co.paystack.android.TransactionManager.initiate(TransactionManager.java:91)
        at co.paystack.android.TransactionManager.chargeCard(TransactionManager.java:105)
        at co.paystack.android.Paystack.chargeCard(Paystack.java:69)
        at co.paystack.android.Paystack.chargeCard(Paystack.java:57)
        at co.paystack.android.PaystackSdk.chargeCard(PaystackSdk.java:151)
        at com.fixy.user.Activities.PaystackActivity.chargeCard(PaystackActivity.java:195)

I am using soap library and exclude okhttp because it shows duplicate okhttp.Address class in soap and square.okhttp

**Comment by michael-paystack** [comment]
This issue should be fixed in newer versions of the SDK.
I'll close this now but please open a new issue if you run into any problems.
