### ISSUE TITLE
move to androidx

### ISSUE THREAD

**Issue by exklinxence** [PaystackHQ/paystack-android#89]
# Problem/Motivation
I am using androidx for my project, just upgraded my android studio to 3.6 and there are clashses with some of your resource file, especially the styllables

## Proposed resolution
i believe if you can create a new version for developers using androidx

## Actual Results:
(What is gave including any error messages, memory dump etc that can help)

**Comment by josephsarz** [comment]
Hi @exklinxence, i bet as you upgraded your android studio you also updated your gradle build, To fix the issue just use a stable version of gradle build tool, make sure its not an alpha or beta release you are using. e.g dont use  `classpath 'com.android.tools.build:gradle:4.0.0-beta02'` instead, use ` classpath 'com.android.tools.build:gradle:3.6.0'`

**Comment by clemokey** [comment]
The latest gradle stable version is 3.6.1 and paystack pinpad still give the following errors about the styllable: `<declare-styleable name="ForegroundView"><attr name="android:foreground"/><attr name="android:foregroundInsidePadding"/><attr name="android:foregroundGravity"/></declare-styleable>` 

`Android resource linking failed
C:\Users\Clement\.gradle\caches\transforms-2\files-2.1\448a86a9112a3b3661edb4e8c812a55e\jetified-pinpad-1.2\res\values\values.xml:7:5-185: AAPT: error: resource android:attr/foregroundInsidePadding is private.
`

`C:\Users\Clement\.gradle\caches\transforms-2\files-2.1\448a86a9112a3b3661edb4e8c812a55e\jetified-pinpad-1.2\res\values\values.xml:7:5-185: AAPT: error: resource android:attr/foregroundInsidePadding is private.
 `

**Comment by josephsarz** [comment]
Hi @clemokey i currently use gradle version `3.5.3`, can you downgrade to this version and check if it works out for you. I think there is a compatibility issue with gradle versions higher than this, but I'm sure `3.5.3` works

**Comment by clemokey** [comment]
yeah, downgrading works.

**Comment by josephsarz** [comment]
Awesome

**Comment by michael-paystack** [comment]
Hi folks.
We released version `3.0.17` today. It should fix this issue. Please try it out and let me know if this issue persists. You'll have to use it with version `1.0.4` of the Pinpad library though.

Thanks.
