### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by deLTreeTech** [PaystackHQ/paystack-android#9]
I'm getting this error on android 4.4 devices:

javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x6241ddf0: Failure in SSL library, usually a protocol error
                                                                        error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x5dfcf6fd:0x00000000)

I noticed the the transaction was logged on my paystack dashboard but I could not get response from the server due to the error. 
I tested the app on 5.0 and above and it worked fine.

**Comment by deLTreeTech** [comment]
I have discovered that the problem came from payment verification. Below is my volley request code. Can you tell me what I'm doing wrong. Thanks

private void verifyPayment(final String paymentRef) {
        // Tag used to cancel the request
        String tag_string_req = "verifyPayStack";
        StringRequest strReq = new StringRequest(Request.Method.GET,
                "https://api.paystack.co/transaction/verify/" + paymentRef, jsonListener, errorListener) {
            @Override
            public Map<String, String> getHeaders() {
                // Posting params to register url
                Map<String, String> params = new HashMap<>();
                params.put("Authorization", "Bearer sk_test_myskkey");
                return params;
            }
        };

        // Adding request to request queue
        AppController.getInstance().addToRequestQueue(strReq, tag_string_req);
    }

**Comment by ibrahimlawal** [comment]
Hello @deLTreeTech this would mean that you are adding your secret key to your app. Please don't do that. Rather do the verification on your app server so your app communicates with your server and your server verifies from our server.

**Comment by deLTreeTech** [comment]
Thanks I will see to that.
