### ISSUE TITLE
 AAPT: error: resource attr/foreground (aka com.softcom.bridgeme.subscriber.android:attr/foreground) not found.

### ISSUE THREAD

**Issue by Emil101** [PaystackHQ/paystack-android#90]
# Problem/Motivation
I added the the following to my gradle file:
  implementation 'co.paystack.android.design.widget:pinpad:1.0.1'
    implementation 'co.paystack.android:paystack:3.0.12' 
and I have been getting this error after building:
 AAPT: error: resource attr/foreground (aka com.softcom.bridgeme.subscriber.android:attr/foreground) not found.

**Comment by josephsarz** [comment]
Hi @Emil101  The problem is with your gradle, There is a compatibility issue with the Paystack Pinpad library, so make sure you are using a stable version of gradle. don't use any alpha or beta release, if you are using any just downgrade.

**Comment by josephsarz** [comment]
use this version of gradle  `classpath 'com.android.tools.build:gradle:3.5.3'`

**Comment by michael-paystack** [comment]
Thanks for helping out @josephsarz 
We made some changes to fix this in version `3.0.14`. Let me know if you're still experiencing issues.
