### ISSUE TITLE
AAPT: error: duplicate value for resource 'attr/foregroundInsidePadding' with config '

### ISSUE THREAD

**Issue by VIROSOFT** [PaystackHQ/paystack-android#93]
I updated my dependencies to:

implementation 'co.paystack.android:paystack:3.0.14'
implementation 'co.paystack.android.design.widget:pinpad:1.0.2'

I updated it today hoping to fix this
"AAPT: error: resource attr/foreground (aka com.package.app.android:attr/foreground) not found." Well the issue was fixed but a new one showed up, and this time it's:
"AAPT: error: duplicate value for resource 'attr/foregroundInsidePadding' with config '".

This issue persists on both gradle version 3.5.3 and 3.6.1, unless I downgrade Paystack dependency to "implementation 'co.paystack.android:paystack:3.0.11" on gradle version 3.5.3, nothing else works.

Please kindly help with this.

**Comment by sholleyonline** [comment]
I'm getting this same error: AAPT: error: duplicate value for resource 'attr/foregroundInsidePadding' with config '' too
I have to downgrade to "implementation 'co.paystack.android:paystack:3.0.11" to get the App runnig.
Please help. Thanks

**Comment by MichaelObi** [comment]
Hi folks. This bug was introduced in the last version we released to fix a similar issue. 
It's now been fixed in version `3.0.17`. You'll have to use version `1.0.4` of the Pinpad library with it.

This issue has now been closed. Thanks for bringing it up.

**Comment by MalcolmTomisin** [comment]
Hi @MichaelObi , so I am getting this error also while trying to compile a release apk, I am using gradle version of 4.1.0 and 'co.paystack.android:paystack:3.1.2'.
